@startuml
'https://plantuml.com/sequence-diagram


class Solution42 {
List<Employee> employeeList
+getFileLine(BufferedReader reader): String String.valueOf(output)
+writeToFile(List<Employee> employeeList): String reader.readLine()
}

class Employee {
String lastName
String firstName
String salary
+outputString()
}
Solution42 o-- Employee
@enduml