@startuml
'https://plantuml.com/sequence-diagram


class Solution42 {
main(String[])
List<String> employee
List<String> l
List<String> f
List<String> s
}

class Employee {
List<String> employees
List<String> lastName
List<String> firstName
List<String> salary
+readFromFile(List<String> employee)
+writeToFile(List<String> lastName, List<String> firstName, List<String> salary): output
+employeeParser(List<String> employees, List<String> lastName, List<String> firstName, List<String> salary)
}
Solution42 o-- Employee
@enduml