@startuml
'https://plantuml.com/sequence-diagram


class Solution42 {
List<Employee> employeeList
+main(String[])
+getFileLine(BufferedReader reader): String
+writeToFile(List<Employee> employeeList): String
}

class Employee {
-String lastName
-String firstName
-String salary
'constructor
+outputString(): String
}
Solution42 o-- Employee
@enduml