@startuml
'https://plantuml.com/sequence-diagram
class Solution43 {
StringBuilder output
+main(String[])
+createWebsiteDirectory(String siteName, StringBuilder output): String siteDirectory
+createWebsiteHTML(String siteNameDir, String siteName, String authorName, StringBuilder output)
+createWebsiteJs(String siteNameDir, StringBuilder output)
+createWebsiteCss(String siteNameDir, StringBuilder output)
}

class Website {
-String siteName
-String siteDirectory
-String authorName
-String jsFolder
-String cssFolder
+setSiteName(String siteName)
+getSiteName()
+getSiteDirectory()
+setSiteDirectory(String siteDirectory)
+setAuthorName(String authorName)
+getAuthorName()
+setJsFolder(String jsFolder)
+getJsFolder()
+setCssFolder(String cssFolder)
+getCssFolder()
}

Solution43 o-- Website
@enduml