@startuml
'https://plantuml.com/sequence-diagram
class Solution41 {
+main(String[])
List<String> personList
'Collections.sort(personList)
+readFromFile(List<String> names)
+writeToFile(List<String> names): output
}


@enduml