@startuml
'https://plantuml.com/sequence-diagram


class Solution45 {
String outputString
String outputFile
+main(String[])
+readAndReplace(): String
+writeToFile(String outputFile, String output)
}
@enduml