@startuml
'https://plantuml.com/sequence-diagram

'only have one class for solution since nothing is being created; each instance of 'utilize' is simply being replaced with 'use'
class Solution45 {
String outputString
String outputFile
+main(String[])
+readAndReplace(): String
+writeToFile(String outputFile, String output)
}
@enduml